from detectron2.utils.registry import Registry


from .build import build_transformer_decoder, TRANSFORMER_DECODER_REGISTRY
from .transformer_decoder_mask_bd_mulkv import TransformerDecoderMask_Boundary_MulKV

